[package]
name = "project_init"
version = "0.1.0"
authors = ["Vanessa McHale <tmchale@wisc.edu>"]
license-file = "LICENSE"
exclude = [ ".gitignore" ]
readme = "README.md"
repository = "https://github.com/vmchale/project-init"
documentation = "https://github.com/vmchale/project-init#README"
homepage = "https://github.com/vmchale/project-init"

[dependencies]
toml = "0.4"
clap = {version = "2.23", features = ["yaml"]}
time = "0.1"
rustache = "0.1"
serde_derive = "1.0"
serde = "1.0"
text_io = "0.1"

#[dependencies.rustache]
#git = "https://github.com/vmchale/rustache.git"

[[bin]]
name = "pi"
path = "src/main.rs"
