[package]
name = "project_init"
version = "3.0.3"
authors = ["Vanessa McHale <vamchale@gmail.com>"]
description = "Quickly initialize projects from a template."
license-file = "LICENSE"
exclude = [ "./.gitignore" ]
readme = "README.md"
repository = "https://github.com/vmchale/project-init"
documentation = "https://github.com/vmchale/project-init#README"
homepage = "https://github.com/vmchale/project-init"
build = "build.rs"

[profile.release]
lto = true

[dependencies]
case = "0.1"
toml = "0.4"
colored = "1.6"
clap = {version = "2.28", features = ["yaml"]}
time = "0.1"
rustache-lists = "0.1.0"
serde_derive = "1.0"
serde = "1.0"
text_io = "<= 0.1.6"
git2 = "0.6"
tempdir = "0.3"

[[bin]]
name = "pi"
path = "src/main.rs"
