license = "BSD3"
with_readme = true

[files]
files = []
directories = ["src"]
templates = ["src/View.elm","src/Update.elm","src/State.elm","src/main.elm","elm-package.json",".gitignore"]

[config]
version = "1.0.0"
version_control = "git"

[[user]]
license_file = "LICENSE"
